runtime: python310
instance_class: F2
entrypoint: bash /app/start.sh

env_variables:
  TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}

automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 80