version: '3.8'

services:
  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: python tele.py
    volumes:
      - ./books:/app/books
    depends_on:
      - fastapi-service
    healthcheck:
      test: ["CMD", "python", "-c", "import os; assert os.path.exists('/app/tele.py')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  fastapi-service:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    volumes:
      - ./books:/app/books
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s